# Generated by Django 4.0 on 2023-04-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_persona_fechanacimiento_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechanacimiento',
            field=models.DateTimeField(),
        ),
    ]
