# Generated by Django 4.0 on 2023-04-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_persona_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechanacimiento',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fechalimite',
            field=models.TextField(),
        ),
    ]
