# Generated by Django 4.0 on 2023-04-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_persona_fechanacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fechanacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fechalimite',
            field=models.DateTimeField(),
        ),
    ]
